# Importing Pandas

In [7]:
import pandas as pd

# Opening local csv file

In [8]:
df_file = pd.read_csv('aug_train.csv').head()
df_file.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

# Opening a csv file from an URL

In [9]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
req = requests.get(url)
data = StringIO(req.text)
df_url = pd.read_csv(data)
df_url.head()

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA

# Sep Parameter

In [16]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genres'])

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

#  Index_col parameter

In [18]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genres'],index_col='sno')

,name,release_year,rating,votes,genres
sno,,,,,
m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...
m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [20]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',
            names=['sno','name','release_year','rating','votes','genres'],index_col='sno',
            usecols=['sno','name','release_year','genres'])

,name,release_year,genres
sno,,,
m0,10 things i hate about you,1999,['comedy' 'romance']
m1,1492: conquest of paradise,1992,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...
m612,watchmen,2009,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
m613,xxx,2002,['action' 'adventure' 'crime']
m614,x-men,2000,['action' 'sci-fi']
m615,young frankenstein,1974,['comedy' 'sci-fi']
m616,zulu dawn,1979,['action' 'adventure' 'drama' 'history' 'war']

# Squeeze DataFrame to Series

In [27]:
pd.read_csv('aug_train.csv',usecols=['enrollee_id']).squeeze()

0         8949
1        29725
2        11561
3        33241
4          666
         ...
19153     7386
19154    31398
19155    24576
19156     5756
19157    23834
Name: enrollee_id, Length: 19158, dtype: int64

# Skiprows/nrows Parameter

In [29]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',
            names=['sno','name','release_year','rating','votes','genres'],index_col='sno',
            usecols=['sno','name','release_year','genres'],skiprows=[1,2])

,name,release_year,genres
sno,,,
m0,10 things i hate about you,1999,['comedy' 'romance']
m3,2001: a space odyssey,1968,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,['action' 'comedy' 'crime' 'drama' 'thriller']
m5,the fifth element,1997,['action' 'adventure' 'romance' 'sci-fi' 'thri...
m6,8mm,1999,['crime' 'mystery' 'thriller']
...,...,...,...
m612,watchmen,2009,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
m613,xxx,2002,['action' 'adventure' 'crime']
m614,x-men,2000,['action' 'sci-fi']
m615,young frankenstein,1974,['comedy' 'sci-fi']
m616,zulu dawn,1979,['action' 'adventure' 'drama' 'history' 'war']

In [30]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',
            names=['sno','name','release_year','rating','votes','genres'],index_col='sno',
            usecols=['sno','name','release_year','genres'],nrows=5)

,name,release_year,genres
sno,,,
m0,10 things i hate about you,1999,['comedy' 'romance']
m1,1492: conquest of paradise,1992,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,['action' 'comedy' 'crime' 'drama' 'thriller']

# Encoding parameter

In [32]:
pd.read_csv('zomato.csv',encoding = 'latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

# dtypes parameter

In [35]:
pd.read_csv('aug_train.csv',dtype={'target':int})

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0

# Handling Dates

In [37]:
pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

# Convertors

In [40]:
def rename(city):
    return city[0]

In [46]:
pd.read_csv('IPL Matches 2008-2020.csv',converters={'city':rename},usecols=['id','city']).head()

       id city
0  335982    B
1  335983    C
2  335984    D
3  335985    M
4  335986    K

# na_values parameter

In [49]:
# to make specific character as NaN, like 
#to replace '-' with NaN values so pandas provides us functions to handle the same
pd.read_csv('aug_train.csv',na_values=['-',])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

# Loading a huge dataset in chunks

In [53]:
dfs = pd.read_csv('aug_train.csv',chunksize = 3000)

In [54]:
for chunk in dfs:
    print(chunk.shape)

(3000, 14)
(3000, 14)
(3000, 14)
(3000, 14)
(3000, 14)
(3000, 14)
(1158, 14)

# Working with JSON

In [55]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [56]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,0.0437
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,0.7880
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,1.0900
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,4.6100
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,0.0213
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,1.3100
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,2.9800
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,0.2100
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,0.3170
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2024-10-27,1729987201,0.3290

# Working with SQL

In [67]:
pip install mysql.connector

Collecting mysql.connector
  Using cached mysql-connector-2.2.9.tar.gz (11.9 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp39-cp39-macosx_10_9_x86_64.whl size=247957 sha256=cb2497f0896b99382b031e82c8c250cb227a78dbc1dfc3c7485945560b3a6131
  Stored in directory: /Users/sandeepkumarreddybollapu/Library/Caches/pip/wheels/ed/d2/ef/350d6d5e22478e792288bdc128a34eb4bb062540097713cbab
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: /Users/sandeepkumarreddybollapu/opt/anaconda3/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [68]:
import mysql.connector

In [70]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [71]:
pd.read_sql_query('SELECT * FROM city',conn)

/Users/sandeepkumarreddybollapu/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

# API

In [78]:
import pandas as pd
import requests

In [79]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=<apiKey>&language=en-US&page=1')

In [87]:
df = pd.DataFrame()

In [90]:
for i in range(1,429):
     response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=<apiKey>&language=en-US&page={}'.format(i))
     temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
     df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)
/var/folders/9l/gs_rnxtj0ml43kbz9r72b4f40000gn/T/ipykernel_29080/315127102.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(temp_df,ignore_index=True)

In [93]:
df.to_csv('movies.csv',index=False)

In [94]:
pd.read_csv('movies.csv')

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,232.368,8.707,27016
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,260.942,8.700,20516
2,1184918,The Wild Robot,"After a shipwreck, an intelligent robot called...",2024-09-12,7140.064,8.606,1729
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,125.095,8.600,12374
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,88.912,8.565,15782
...,...,...,...,...,...,...,...
8555,9966,The Messengers,When the Solomons trade in the craziness of bi...,2007-02-02,40.597,5.700,793
8556,41517,Ra.One,When the titular antagonist of an action game ...,2011-10-24,29.354,5.700,328
8557,14289,Fire Down Below,When an EPA representative is murdered in a sm...,1997-09-05,23.015,5.700,349
8558,9038,The Heartbreak Kid,"Eddie, the 40-year-old confirmed bachelor fina...",2007-10-05,23.633,5.726,1586
8559,312669,Maggie's Plan,Maggie's plan to have a baby on her own with a...,2016-04-27,16.197,5.700,374